server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/apple1-23/springcloud-config.git
          #uri: git@github.com:apple1-23/springcloud-config.git  #GitHub上面的git仓库名字
          search-paths: #搜索目录
            - springcloud-config
          username: 2838839039@qq.com
          password: apple123
      label: master     #读取分支
  #rabbitmq相关配置
  rabbitmq:
    host: 192.168.153.131
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
