server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          #uri: git@github.com:apple1-23/springcloud-config.git  #GitHub上面的git仓库名字
          search-paths: #搜索目录
            - springcloud-config
          username: 2838839039@qq.com
          password: apple123
          uri: https://github.com/apple1-23/springcloud-config.git
      label: master     #读取分支

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
